### PR TITLE
Using a mirror with pmm

### PR DESCRIPTION
**Pull request by wong2**
[pmm](https://github.com/wong2/pmm), aka PyPi Mirror Manager, is a cli tool I build to change PyPi mirror conveniently, it's using data from python-mirrors.org

### CODE REVIEW

**Comment by wong2** [comment]
咦原来是你，人生何处不相逢

**Comment by ibigbug** [comment]
哈哈，换个地方继续

**Comment by ibigbug** [comment]
shipped: https://pypi-mirrors.org/

**Comment by wong2** [comment]
🆒

**Pull request merged**
